### ISSUE TITLE
zps_blackout - Just black when looking out or at a window

### ISSUE THREAD

**Issue by maisteven** [ZPSNMRiHIssues/zpsissues#17]
As the picture shows, it's just black when staring at the window but when I walk up alittle closer, the textures outside show up normally. 

![2013-04-07_00001](https://f.cloud.github.com/assets/4086530/349348/7c18fc82-9fbd-11e2-9c06-97031224b8bc.jpg)

Edit:
Here's the window after taking a few steps forward
![2013-04-07_00004](https://f.cloud.github.com/assets/4086530/349438/cd3a05ce-9fc3-11e2-88b1-fdb68012dc18.jpg)

**Comment by Jonny-Steel** [comment]
Yes, that's basically intentional. Or let's say necessary. It's an func_areaportalwindow. This: https://developer.valvesoftware.com/wiki/Func_areaportalwindow

I use these special windows to hide interior or exterior geometry, dependent where you are standing. If you far away, the portal will be closed and stops rendering objects behind it. Thats important to do not kill the frame rate on this map.

I added a reflection to all other, not broken windows, to mask this effect a little. But in this special case the window is broken and has no window glass anymore. That's why there is no reflection, only the pitch black effect. Sorry, nothing to do/fix here. It has to be how it is.

--- Bug report can be closed. ---
