### ISSUE TITLE
[SUGGESTION] [ZP!S SDK 2013] Nerfing Sledgehammer Headshot DMG 

### ISSUE THREAD

**Issue by KamepeLaeske** [ZPSNMRiHIssues/zpsissues#200]
Reduce the dmg on headshots from 240 dmg to 200 dmg.

**Comment by Tabajara77** [comment]
I suggest reducing to 190 to give one more chance for regular zombies.

**Comment by xerox8521** [comment]
What you have to take into consideration is that the sledgehammer is pretty slow compared to other melee weapons.

**Comment by KamepeLaeske** [comment]
I have. The sledgehammer has a really long range which makes it easy to kite zombies with it. Having it a one-shot kill on regular zombies is simply too much considered how easy it is to use compared to something like the magnum. Making it a two-shot kill is in my opinion the best option. 

To elaborate;

In a confrontation between a survivor with a sledgehammer and a zombie, the survivor is almost certain to get the first hit in because of the sledgehammers range. Combine that with the weapons ability to kite zombies around, and it makes it being a one-shot kill way too powerful - Especially with better hitboxes :P

**Comment by NjMuffin** [comment]
I can't agree with that at all. The point of the sledgehammer is that this weapon is meant to be a powerful 1 vs 1 or even 1 vs 2 melee, it has the highest melee base damage and in right hands this weapon becomes basically a melee ranged magnum which allows the player to deal with normal zombies with one 'headshot' hit but a the same time this weapon has also the slowest attack speed which makes it weak against a group of zombies, sure you can take out one of them but the time frame between the hits is so huge it allows a zombie to hit the survivor two times and if there is an entire group of them then most of the times the survivor goes down very quickly.
With better hitboxes it will be also easier for the zombies to hit survivors and even in 1v1 situations if a zombie manages to bait survivor's swing then it is a large time frame for this zombie to land at least one hit on the survivor. 
I rather think the golf club needs a proper rework since this weapon is worse than a crowbar.
