### ISSUE TITLE
[SUGGESTION] [ZP!S SDK 2013] Give the pistols different stats 

### ISSUE THREAD

**Issue by KamepeLaeske** [ZPSNMRiHIssues/zpsissues#201]
As of right now all the pistols have the same stats. I think this should be changed to create more variety among the pistols. It would also help with the communitys request for more weapons, as they pistols will now have their own unique advantages and  disadvantages. 

Here is the currrent dmg output for all pistols: Power: 14 (Per body shot) 42 (Per headshot)

My suggestions;
## PPK

Power: 20 (Per body shot) 50 (Per headshot) 
Accuracy: Very accurate. 

The PPK only has 7 bullets in it which I tink justifies making it 'the magnum' of the pistols. It's perfect for a high risk/high reward weapon. 
## USP

Power: 17 (Per body shot) 42 (Per headshot) 
Accuracy: Good 

I think the current stats are fine for the USP, given that its very common and has a clip of 15 bullets. 
## Glock17

Power: 15 (Per body shot) 38 (Per headshot) 
Accuracy: Very accurate, but not as accurate as the PPK 

Given it has more bullets than the USP and has a very slim look, I feel like the Glock17 should have lower damage but higher accuracy compared to the USP. 
## Glock18

Power: 17 (Per body shot) 42 (Per headshot) 
Accuracy: Decent

Glock18 appears to be a better version of the glock17, so I think it should keep the stats of the USP, making it more powerful than the glock17, but have a lower accuracy compared to the glock17.

**Comment by Will-Tango** [comment]
As far as I know headshot's are simply triple the damage of a body shot.
eg pistol 14 x 3 = 42
If the Glock18 damage was increased to 17 the headshot damage may have to be increased to 51.
Also if humans spawn late they are given a PPK rather than a random pistol, this would probably need to be changed to stop everyone from spawning late to get a PPK.

**Comment by KamepeLaeske** [comment]
Yeah, it is. I think we risk making pistols too powerful(or too weak) if we stick with the headshot = body x 3 formular as it is best suited for an arsenal that has the exact same stats. I think it's best to tweak the stats individually and not rely on a base formular, at least not the one that is currently been used to make the pistols do the exact same damage. The formular needs to account for clip size and accuracy as well.

All of these stats would require a serious amount of playtesting to make sure that the tweaks are balanced, though. I agree that the PPK should not be the weapon that late-joiners recieve anymore :)

**Comment by NjMuffin** [comment]
Glock18 always feels for me like a 'spam-them-out-weapon'; it is still good enough to deal with zombies but with since it has the highest recoil ( or at least should have) it is there to weaken them for other survivors so they don't have to use up more ammo than needed. In other words high fire rate, high magazine size but also high recoil for spamability.
Glock17 could be a hybrid between Glock18's high magazine size and USP's precision but lower damage.
USP could have 12 bullets instead of 15, slower firerate but slightly increased damage.
PPK is usually meant as punishment for late joiners, but giving it a higher damage boost isn't a bad idea since with its low magazine size it is really good for a single target but bad to deal with a horde.
Just my few coins on this topic.
