### ISSUE TITLE
[SDK 2013 Request]Show Survivor's name in MP Options

### ISSUE THREAD

**Issue by Tabajara77** [ZPSNMRiHIssues/zpsissues#203]
Besides showing "survivor 1";"survivor 2";"survivor 3";"survivor 4;""survivor 5"
Display their real name instead: Euguene, Marcus, Jessica, Paul, Lea, Vanessa.

**Comment by jonnyboy0719** [comment]
This will be implemented, and a more updated preview images will be added instead of their "ragdoll" pose

**Comment by GunF0x** [comment]
I think an even easier way to select character should be implemented. Not
many players go to their multiplay options to switch unless they happen to
know. Perhaps a main menu "character select" option would be a better
solution. Not saying I personally care, but I know a lot of players
(anecdotal) who play games based upon the avatar they are allowed to use
that they find "cool/fun".

I wouldn't say it's a pressing issue, but the little things do add up when
it comes to ease of use and a free mod.

On Sep 1, 2016 12:16 PM, "Johan Ehrendahl" notifications@github.com wrote:

This will be implemented, and a more updated preview images will be added
instead of their "ragdoll" pose

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/ZPSNMRiHIssues/zpsissues/issues/203#issuecomment-244148097,
or mute the thread

**Comment by jonnyboy0719** [comment]
The character selection has been moved to the mainmenu, due valve broke the original code under the multiplayer tab on SDK 2013. And now the survivors use their real names, instead of "Survivor1" etc.
