### ISSUE TITLE
[SDK 2007] Possible oversight in weapon weight ?!

### ISSUE THREAD

**Issue by xerox8521** [ZPSNMRiHIssues/zpsissues#208]
Hi, so im not sure if this is intended or not but i have been testing around and found out that weapon_bat_aluminum and weapon_bat_wood don't have any weight while all other guns / melees do have weight.

**Comment by jonnyboy0719** [comment]
All melee weapons shouldn't have any weight on them, only firearms & ammo should slow you down (and armor, if equipped)

**Comment by GunF0x** [comment]
As far as I know the only weapon meant to not have weight was the wooden
plank. Bats did at one point have weight as far as I can remember. Makes
sense that they would as well, though I can see how a metal bat would weigh
a bit less than a wooden one.

**Comment by xerox8521** [comment]
I dont agree that melees shouldnt have weight. I mean you wouldnt run at full speed with a sledgehammer in your hand.

**Comment by GunF0x** [comment]
You misunderstood. There is one weapon that should not have weight, due to
its impossibly low damage and the fact that it is an impromptu weapon. All
other weapons should have weight, even if it is negligible.

**Comment by xerox8521** [comment]
Nah i meant jonny as he said melees shouldnt have any. Im ok with the plank not having weight. But like you said any other melee should have weight.

**Comment by GunF0x** [comment]
Specifically the sledge should have a significant weight and slow swing
time to account for that. If melee weapons have no weight, what's to stop
people from abusing the knock back and panic command? I do not see why any
weapon aside from the tiny broken plank of wood should not have weight.

On Sep 1, 2016 1:01 PM, "Alexander the Great" gunf0xy@gmail.com wrote:

You misunderstood. There is one weapon that should not have weight, due to
its impossibly low damage and the fact that it is an impromptu weapon. All
other weapons should have weight, even if it is negligible.

**Comment by KamepeLaeske** [comment]
Jonnyboy was referring to the weapon scripts from the game, not our plans for the next update. Adding appropiate weight to the melee weapons is something we'll do for an future update :)

**Comment by jonnyboy0719** [comment]
Has now been fixed
