### ISSUE TITLE
[REQUEST] [SOURCE SDK 2013] Change voice menu

### ISSUE THREAD

**Issue by BreakinBenny** [ZPSNMRiHIssues/zpsissues#221]
Ever since I played ZPS, I've been used to closing the menu while having my cursor over an option. Some updates later it requires clicking, and I don't appreciate this system compared to that in Counter-Strike, or Team Fortress when it was easy. Left 4 Dead's radialmenu was pretty good, even though it allowed spamming stuff through the "vocalize" command and PlayerDeath and stuff.

Will you please use the VoiceCommands.txt? It's the standard for pre-Left 4 Dead games and is much easier to translate without making custom graphics for each voice option. Don't forget those "zps_%language%.txt files either!

**Comment by xerox8521** [comment]
Radial menu like in L4D would be good. With an build in protection so ppl cannot spam it (CVar to configure it ? ).

**Comment by jonnyboy0719** [comment]
Radial menu in L4D was mostly possible due to engine upgrade, this is possible in Alien Swarm SDK (Using L4D as a base), but not in SDK 2013. So we will stick with normal image one. And before anyone asks, porting SDK 2007 (or 2013) to Alien Swarm is too much un-needed work, because you would need to re-write it back to FPS, and everything else, it's not really worth it.

**Comment by BreakinBenny** [comment]
So in other words, you'll _stick_ with this graphics-based voicemenu... Whatever you say, guys.
