### ISSUE TITLE
[SDK 2007] GiveNamedItem issue with aluminum baseball bat

### ISSUE THREAD

**Issue by xerox8521** [ZPSNMRiHIssues/zpsissues#229]
There is an issue if you call CHL2MP_Player::GiveNamedItem with the weapon_bat_aluminum as param it doesnt seem to work it just returns -1 as entity index. This should be looked into. So far no other gun or melee weapon has that issue. Current fix would be probably to just create the weapon entity and then manually call pickup so it works properly.

**Comment by jonnyboy0719** [comment]
I assume you run the _GiveNamedItem_ trough sourcemod predefined tables. on the gamedata txt file, which in return can cause issues.

**Comment by xerox8521** [comment]
No im using this signature "@_ZN13CHL2MP_Player13GiveNamedItemEPKc"

**Comment by jonnyboy0719** [comment]
_ZN13CHL2MP_Player13GiveNamedItemEPKc_ is retrieved from the sdk2007 gamedata or zps gamedata. ZPS has its GiveNamedItem changed, which is why it breaks. It would be better if you use smlib instead, or create the entity manually.

If SourceMod related stuff are broken, it would be best if you ask the SM Community instead, not here.
