### ISSUE TITLE
[2013 Request] Proximity Voice Chat via Phone (J) Hardcore Mode

### ISSUE THREAD

**Issue by Tabajara77** [ZPSNMRiHIssues/zpsissues#231]
On the default hardcore mode (sv_hardcore 1) it will work as it should be. No huge changes compared to the current Steam build (2.4); but on another hardcore level (sv_hardcore 2), Jonny managed to create something even more cool with voice chat. But that would work more harder if the player could only talk with his team mates only (TEAM) via his phone - while holding Motorola on his hand - or maybe even make phone as a slot inventory: if you drop it, you are not allowed to talk via voice chat until you find a new/same phone.

Edit: **_As Optional**_ Make the phone (J) be use for voice chating only. C4 would be triggered by radius sensitive if any zombie gets closer to it, would blow up; increasing the damage and the radius blast.

More realistic and hardcore.

**Comment by jonnyboy0719** [comment]
Sounds interesting, will maybe add this on the 3.1 update.

**Comment by DoofusCockslap** [comment]
Hey, maybe use not "sv_hardcore" cvar, but add a new cvar like "sv_realism"? That would make more sense because there will be still a normal gameplay with no ZPH mode features active in other modes. 
Also adding this kind of feature in ZPH is not a good decision since there is no time for people to pull out the phone just to talk.. ZPH is just too fast for this stuff. 

Dropping phone feature is just too much, especially the fact that you can't talk over the voice chat lol
Imagine how the new players will be confused because they dropped their phone from inventory and can't even communicate with the team without even knowing it. 
This means - you may "mute" yourself without any purpose..

Also IED proximity feature would be very OP because people will abuse it too much and manual triggering will lose its value..

**Comment by xerox8521** [comment]
It would reduce the lacking teamplay even more. Also I think it doesn't fit the hardcore mode.
