### ISSUE TITLE
zps spawn  room

### ISSUE THREAD

**Issue by TheCimeran** [ZPSNMRiHIssues/zpsissues#24]
when spawning in as a zombie on zps_blackout I spawned in room 302 and the doors and floor texture were pink and black boxes. I also heard the noise of being on a breathing machine.

**Comment by Jonny-Steel** [comment]
Yes thx, I forgot to upload these custom textures (room 302) to the DevBuild. I will fix it.

The "breathing noise" in this room is intentional. It's one of the zombie sounds from HL2 and should subliminally tell you, that you are standing inside a zombie spawn area.

--- Bug report can be closed. ---
