### ISSUE TITLE
Shooting and pressing N at the same time with shorty or 870 makes fast shoots.

### ISSUE THREAD

**Issue by ghost** [ZPSNMRiHIssues/zpsissues#73]
If you get remmy or supershorty, and shoot in the same time you pressed n for unload, you shoot the round you unload + the next round, making 2 shots in a row.

Demo with proof: http://fastdl.cfbk.com.br/demos/shotgun.dem

**Comment by Smil3yRiley** [comment]
Please use youtube to record your stuff, sometimes I'm not on my PC to view these demo files!

**Comment by ghost** [comment]
Just recorded and uploaded to youtube now: http://www.youtube.com/watch?v=_zCVrq3XhzA&feature=youtu.be

**Comment by Smil3yRiley** [comment]
Taking a closer look at this, it doesn't look like you're actually firing 2 shells for real in the game; to the client (you) you're firing two shots, but the server only registers one shot (since your ammo count is still the same)

It's sort of like firing a pistol but immediately quick switching it for another weapon, it looks like you fired a damaging shot without using ammo but nothing actually happens

**Comment by ghost** [comment]
so its all client-side? lol, the strange stuff is the blood coming out of zombies and the shots on the wall

**Comment by neoassassin** [comment]
All the decals are client side as well, blood splatter and bullet holes, so that's why they're produced as well.
